### ISSUE TITLE
Adding additional ARM support for uClock (Adafruit QT Py M0)?

### ISSUE THREAD

**Issue by m-r-m-s** [midilab/uClock#17]
Hi @midilab, 

I have been working with another ARM board, the [Adafruit QT Py M0](https://learn.adafruit.com/adafruit-qt-py) which is pin compatible to the Seeed Xiao board with a few hardware differences. Honestly it is a little bit easier to work with on development side and it also uses the current version of the Adafruit Tiny USB library unlike the Seeed Xiao.

Since the Adafruit M0 board is so similar, I thought it would be an easy switch over to using it since you updated the uClock library to support the Xiao. 

However, the [Arduino core for the QT Py board ](https://github.com/adafruit/ArduinoCore-samd/tree/master/libraries)does not include the same `TCC0` and `TC3` helper libraries as the Xiao SAMD implementation unfortunately. Those libraries are actually based of the work of this timer interrupt library that I believe should work with the QT Py M0: https://github.com/khoih-prog/TimerInterrupt_Generic

Here is an example of using hardware timers directly:
https://github.com/khoih-prog/TimerInterrupt_Generic#1-using-only-hardware-timer-directly-1

The MACRO for the QT Py M0 can be `__SAMD21E18A__` or `ADAFRUIT_QTPY_M0`

Using the above example, I started to try and figure out how to implement in `uClock.cpp` but got stuck. 
Specifically:

1) What value should `#define TIMER_INTERVAL_MS`  be?

2) What the if def should be for  `uclockInitTimer()` ? Maybe:
```
#if defined(ADAFRUIT_QTPY_M0)
     ITimer.attachInterruptInterval_MS(init_clock, uclockISR)
#endif
```
3) What the if def should be for `void uClockClass::setTimerTempo(float bpm)` ?

Sorry I can't be more helpful to do a pull request but I hope this gets the process going. Thanks!

**Comment by midilab** [comment]
hey @m-r-m-s , thanks for the implementation details! i will incorporate it to the uClock as soon as possible.

**Comment by midilab** [comment]
> 1. What value should `#define TIMER_INTERVAL_MS`  be?

This is used only for AVRs, i think i will start to divide files per port.

**Comment by midilab** [comment]
its the same mcu used by arduino zero by the way:
https://github.com/adafruit/Adafruit_ZeroTimer/

**Comment by midilab** [comment]
Well after some hang about this issue i discovery that Tc3 library is bugged, also its marked as legacy already. So far looks like TCC0 library work as expected but i didnt conduct some deep tests to make sure, any way i think the best solution will be to port the usage of TCx or TCCx for directly register access, that will probrably usable on a wide range of SAMDxx.

Thanks god you found this library: https://github.com/khoih-prog/TimerInterrupt_Generic wich looks good to use as port.

The reason i decide to make the whole port is because the uCtrl that makes use of Tc3 while uClock makes use of TCC0 on uMODULAR environments.

I will send news as soon as i get something done!

Once again thanks for the research over samd timers.

**Comment by mightycoco** [comment]
Tbh. I see this library usefull in an application but not in a library like uClock. The timerinterrupt_generic doesn't seem to play well, if you are already using timer stuff in your application. Having now a dependancy to uClock which depends on tc_generic would force you, to change your app to also use tc_generic (from what I understood)
Also there are a lot of prerequisites using tc_generic like patching the sdk and some files for different boards - from what I have seen in a quick read.

Maybe I'm wrong and would have to see this in a dedicated fork.

**Comment by midilab** [comment]
well the ideia was just to get the part of the code that handles the Timer(form SAMDx) at register level to implement a call at uClock to initialize the timer and to change the frequency but not to incorporate the whole library, but i just give up when i check that this library still needs a lot of patches.

**Comment by midilab** [comment]
> @midilab Thanks for looking into additional porting for uClock. Sounds like it is too much hassle unfortunately. I really appreciate the time trying to make it work! I think I can just work with just adding the TCC0 and TC3 helper libraries to Adafruit Arduino Core like I did when testing.

Well i think it worth to take a note at README about this hacky way to use it with QT Py M0 for those who wish to.
I will update a note with your description of how to do it.

My guess is that soon or later a timer libirary will be oficially integrated into their SDK for arduino.

Thanks for the research too! it is always good for a project to grow and extend as much as possible.

The whole goal behind uClock and uCtrl is exacly that, make it portable on Arduino platform to as many board as we can.

**Comment by midilab** [comment]
Thanks for testing out @m-r-m-s ! in case of any updates on a official library please open another issue for integration.
